version: '3.9'

services:
  api:
    build:
      context: ./api
    command: pnpm run dev
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env.example
    depends_on:
      - db
      - minio
      - mailpit
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata: {}
  minio: {}
