version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm_saas
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: crm_saas
      MINIO_ROOT_PASSWORD: crm_saas_secret
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
  mailpit:
    image: axllent/mailpit:v1.17
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'
volumes:
  postgres-data:
  minio-data:
